services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    container_name: thinkcateln_frontend
    env_file:
      - ./.env
    environment:
      PORT: 3003
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      NEXTAUTH_SECRET: "thinkcateln_secret"
      NEXTAUTH_URL: "http://192.168.1.20:3003"
      NEXT_PUBLIC_ENV: "dev"
      NEXT_PUBLIC_API_BASE_URL: "http://192.168.1.20:8008"
      BACKEND_URL: "http://backend:8008"
    ports:
      - "3003:3003"
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    # command: sh -c "npm install && npm run dev -- -p 3003 -H 0.0.0.0"
    command: npm run dev -- -p 3003 -H 0.0.0.0
    depends_on:
      - backend

  backend:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    container_name: thinkcateln_backend
    env_file:
      - ./.env
    environment:
      ENV: "dev"
      API_BASE_URL: "http://backend:8008"
    ports:
      - "8008:8008"
    volumes:
      - ./backend:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0 --port 8008
      --reload --reload-dir /app 
      --log-level debug
    # depends_on:
      # - db