services:
  gpu_backend:
    build:
      context: .
      dockerfile: Dockerfile.gpu_backend
    container_name: ipforce_gpu_backend
    restart: always
    env_file:
      - .env
    environment:
      ENV: "prod"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    ports:
      - "80:80"  # 외부 7001 → 내부 7001
    volumes:
      - ./gpu_backend:/app
    command: [
      "uvicorn", "app.main:app",
      "--host", "0.0.0.0",
      "--port", "80"
    ]
      # "--ssl-certfile", "/app/certs/ipforce.co.kr_20250108BDFA3.all.crt.pem",
      # "--ssl-keyfile", "/app/certs/ipforce.co.kr_20250108BDFA3.key.pem"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
