version: "3.9"

services:
  frontend:
    build:
      context: ..
      dockerfile: ./infra/docker/Dockerfile.frontend
    container_name: ipforce_frontend
    env_file:
      - ../.env
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:8000"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      BACKEND_URL: "http://backend:8000"             # NextAuth authorize()에서 사용
      NEXTAUTH_URL: "http://192.168.1.20:3000"       # 세션 쿠키를 쓸 실제 도메인
      NEXTAUTH_SECRET: "ipforce_secret"             # 세션 서명용 암호 (임의 문자열)
    ports:
      - "3000:3000"
    working_dir: /app/frontend
    volumes:
      - ../frontend:/app/frontend
      - /app/frontend/node_modules
    command: sh -c "npm install && npm run dev -- -p 3000 -H 0.0.0.0"
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: ./infra/docker/Dockerfile.backend
    container_name: ipforce_backend
    env_file:
      - ../.env
    environment:
      ENV: "dev"
      PYTHONUNBUFFERED: "1" # print 버퍼링 방지
      WATCHMEDO_USE_POLLING: "1" # 도커 볼륨 감지 안정화
      API_BASE_URL: "http://backend:8000"
      GPU_BACKEND_URL: "http://gpu_backend:8000"
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app
      --reload-mode poll
      --workers 1
    depends_on:
      - db
      - gpu_backend

  gpu_backend:
    build:
      context: ..
      dockerfile: ./infra/docker/Dockerfile.gpu_backend
    container_name: ipforce_gpu_backend
    env_file:
      - ../.env
    environment:
      ENV: "dev"
      PYTHONUNBUFFERED: "1"
      WATCHMEDO_USE_POLLING: "1"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    ports:
      - "8001:8000" # 외부 8001 → 내부 8000
    volumes:
      - ../gpu_backend:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app
      --reload-mode poll
      --workers 1 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  db:
    image: mariadb:11
    container_name: ipforce_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ipforce
      MYSQL_USER: ipforce_user
      MYSQL_PASSWORD: ipforce_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  default:
    name: ipforce_network
    driver: bridge